-- employees 테이블에서 전체 내용을 조회
SELECT
	*
FROM
	EMPLOYEES e ;

-- first name, last name, job id
SELECT
	FIRST_NAME ,
	LAST_NAME ,
	JOB_ID
FROM
	EMPLOYEES e ;
	
-- 사원번호가 176인 사람의 LAST NAME과 DEPARTMENT_ID조회
SELECT
	LAST_NAME ,
	DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	EMPLOYEE_ID = 176

-- 연봉이 12000 이상 되는 직원들의 LAST_NAME과 SALARY 조회
SELECT
	LAST_NAME ,
	SALARY 
FROM
	EMPLOYEES e
WHERE
	SALARY >= 12000

-- 연봉이 5000에서 12000의 범위 이외인 사람들 LASTNAME SALARY조회
SELECT
	LAST_NAME ,
	SALARY
FROM
	EMPLOYEES e
WHERE
	SALARY NOT BETWEEN 5000 AND 12000;

-- 부서번호가 20 혹은 50 부서에서 근무하는 사원 LAST_NAME, DEPT_ID조회
-- last name, dept id 오름차순
SELECT
	LAST_NAME ,
	DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	DEPARTMENT_ID IN (20, 50)
ORDER BY LAST_NAME, DEPARTMENT_ID;

-- 커미션을 버는 모든 사원들의 LAST_NAME, SALARY, COMMISION_PCT조회
SELECT
	LAST_NAME,
	SALARY,
	COMMISSION_PCT
FROM
	EMPLOYEES e
WHERE
	COMMISSION_PCT IS NOT NULL
ORDER BY SALARY DESC , COMMISSION_PCT DESC;

--salary가 2500,3500,7000이 아니며 Job이 sa_rep나 ST_CLERK사원조회
SELECT
	*
FROM
	EMPLOYEES e
WHERE
	SALARY NOT IN (2500, 3500, 7000)
	AND JOB_ID IN ('SA_REP', 'ST_CLERK');

-- 2017-01-01~ 2017-12-31사이에 고용된 사원들의 LAST_NAME, EMPLOYEE_ID, HIRED_DATE
SELECT LAST_NAME, EMPLOYEE_ID, HIRE_DATE
FROM EMPLOYEES e
WHERE HIRE_DATE >= '2017-01-01' AND HIRE_DATE <= '2017-12-31';

SELECT
	LAST_NAME,
	EMPLOYEE_ID,
	HIRE_DATE
FROM
	EMPLOYEES e
WHERE
	HIRE_DATE BETWEEN '2017-01-01' AND '2017-12-31';

--부서번호가 20, 50 부서에서 근무하고 연봉이 5000~12000사이인 사원들의 LAST_NAME, SALARY 조회
SELECT LAST_NAME, SALARY
FROM EMPLOYEES e 
WHERE DEPARTMENT_ID IN (20,50) AND SALARY BETWEEN 5000 AND 12000
ORDER BY SALARY ;

-- 2017년에 고용된 사원들 LAST_NAME,  EMPLOYEE_ID, HIRE_DATE 조회
SELECT LAST_NAME,  EMPLOYEE_ID, HIRE_DATE
FROM EMPLOYEES e 
WHERE EXTRACT (YEAR FROM HIRE_DATE) = 2017
ORDER BY HIRE_DATE DESC;

-- 연봉이 5000에서 12000의 범위 이외인 사람들 LASTNAME SALARY조회
SELECT
	LAST_NAME ,
	SALARY
FROM
	EMPLOYEES e
WHERE
	SALARY NOT BETWEEN 5000 AND 12000;
















